### ISSUE TITLE
resume error

### ISSUE THREAD

**Issue by RookieHuang** [zhangcheng828/MonoDetector#5]
When I train some epoch with ddp mode and resume the checkpoint with single_gpu mode. The code doesn't work, it seems has some problems in loading or saving checkpoint.
error as follow:
Traceback (most recent call last):
  File "tools/test.py", line 57, in <module>
    engine.load_checkpoint(args.checkpoint_file, verbose=True)
  File "/workspace/MonoDetector/tools/../engine/base_engine.py", line 208, in load_checkpoint
    self.model.load_state_dict(state_dict['model'])
  File "/opt/conda/libs/test.py", line 57, in <module>
    engine.l/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BaseMonoDetector:
        Missing key(s) in state_dict: "head.heatmap_head.1.weight_", "head.heatmap_head.1.bias_", "head.wh_head.1.weight_", "head.wh_head.1.bias_", "head.offset_head.1.weight_", "head.offset_head.1.bias_", "head.center2kpt_offset_head.1.weight_", "head.center2kpt_offset_head.1.bias_", "head.kpt_heatmap_head.1.weight_", "head.kpt_heatmap_head.1.bias_", "head.kpt_heatmap_offset_head.1.weight_", "head.kpt_heatmap_offset_head.1.bias_", "head.dim_head.1.weight_", "head.dim_head.1.bias_", "head.depth_head.1.weight_", "head.depth_head.1.bias_", "head.dir_feat.1.weight_", "head.dir_feat.1.bias_".

**Comment by Ep11phany** [comment]
Also encountered the same problem. Have you solved it?

**Comment by Ep11phany** [comment]
Maybe the test.py should be modified to adapt `DDPEngine`. Trying.
